# Generated by Django 5.0.1 on 2024-01-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254)),
                ('Phone_no', models.BigIntegerField()),
                ('Message', models.CharField(max_length=30)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=25, null=True)),
                ('Phone_no', models.BigIntegerField()),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Conf_Password', models.CharField(max_length=20, null=True)),
                ('Reg_Date', models.DateTimeField(auto_now_add=True)),
                ('Role', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Comment', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.TextField()),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Payment_mode', models.CharField(choices=[('0', 'OFFLINE'), ('1', 'ONLINE')], max_length=25)),
                ('Pay_Status', models.CharField(choices=[('0', 'PENDING'), ('1', 'CONFIRM'), ('2', 'CANCEL')], max_length=3)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holder_name', models.CharField(max_length=25)),
                ('Expire', models.DateTimeField(auto_now_add=True)),
                ('Price', models.FloatField()),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=25)),
                ('Product_description', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('Product_price', models.FloatField()),
                ('Product_Status', models.CharField(choices=[('0', 'NOT AVAILABLE'), ('1', 'AVAILABLE')], max_length=3)),
                ('Cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.FloatField()),
                ('Cart_Status', models.CharField(choices=[('0', 'PENDING'), ('1', 'CONFIRM'), ('2', 'CANCEL')], max_length=3)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('Photo', models.ImageField(upload_to='photos')),
                ('Gender', models.CharField(choices=[('0', 'MALE'), ('1', 'FEMALE'), ('2', 'OTHER')], max_length=10)),
                ('Address', models.TextField()),
                ('City_name', models.CharField(max_length=30)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
