# Generated by Django 5.0.1 on 2024-01-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Email_id',
            new_name='Email',
        ),
    ]
