# Generated by Django 5.0.1 on 2024-02-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_email_id_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Quantity',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
