# Generated by Django 5.0.1 on 2024-02-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
