# Generated by Django 5.0.1 on 2024-02-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='Subject',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Message',
            field=models.TextField(),
        ),
    ]
