# Generated by Django 5.0.1 on 2024-02-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_us_subject_alter_contact_us_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='Name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
