# Generated by Django 5.0.1 on 2024-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact_us_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
