# Generated by Django 5.0.1 on 2024-02-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_old_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
