# Generated by Django 5.0.1 on 2024-03-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_title', models.CharField(max_length=100)),
                ('Store_image', models.ImageField(upload_to='photos')),
                ('Store_desc', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
