# Generated by Django 5.0.1 on 2024-03-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_complain_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
