# Generated by Django 5.0.1 on 2024-03-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_complain_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Message',
            field=models.TextField(null=True),
        ),
    ]
