# Generated by Django 5.0.1 on 2024-03-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_complain_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='Login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
