# Generated by Django 5.0.1 on 2024-03-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_complain_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='Login_id',
        ),
    ]
