# Generated by Django 5.0.1 on 2024-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_complain_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Login_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
    ]
