# Generated by Django 5.0.1 on 2024-03-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_feedback_login_id_feedback_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='Finaltotal',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Email',
        ),
        migrations.AddField(
            model_name='complain',
            name='Login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
