# Generated by Django 5.0.1 on 2024-03-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_finaltotal_order_finaltotal_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Pay_Status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'CONFIRM'), ('2', 'CANCEL')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_mode',
            field=models.CharField(choices=[('0', 'OFFLINE'), ('1', 'ONLINE')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
