# Generated by Django 5.0.1 on 2024-03-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_order_finaltotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='Pay_Status',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_mode',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
