# Generated by Django 5.0.1 on 2024-03-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_order_product_id_alter_order_pay_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
