# Generated by Django 5.0.1 on 2024-03-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Product_id',
        ),
    ]
