# Generated by Django 4.1.2 on 2024-03-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='STATUS',
            field=models.CharField(choices=[('placed', 'placed'), ('cancel', 'cancel')], default='placed', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(choices=[('AVL', 'Available'), ('NA', 'Not Available')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
