# Generated by Django 5.0 on 2024-04-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_store_user_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoncard', models.CharField(max_length=40)),
                ('card_number', models.CharField(max_length=16)),
                ('card_cvv', models.CharField(max_length=3)),
                ('exp_date', models.CharField(max_length=10)),
                ('card_balance', models.FloatField()),
            ],
        ),
    ]
